# Generated by Django 3.2.10 on 2022-08-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220825_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_corrent',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True, default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_answers',
            field=models.BooleanField(blank=True, default=False, max_length=10),
        ),
    ]
